name: PHP Coding Standards

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: cs2pr, phpcs

      - name: Install WordPress Coding Standards
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require --dev wp-coding-standards/wpcs:"^3.0"

      - name: Run PHPCS
        run: phpcs -q --report=checkstyle --standard=phpcs.xml.dist . 2>/dev/null | cs2pr
